Crow_app/products/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, TextAreaField, IntegerField, SelectField, FileField
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms import ValidationError
from Crow_app.models import User


class NewProduct(FlaskForm):
    user_id = IntegerField(validators=[DataRequired()])
    owner = StringField(validators=[DataRequired()])
    name = StringField('Name', validators=[DataRequired()])
    description = StringField("Description")
    part_id = IntegerField('Part ID')
    main_photo = FileField('Main photo')
    status = SelectField('Status',
    validators=[DataRequired()],
    choices=[('public', 'Public'), ('private', 'Private')])
    submit = SubmitField('Add new product')

Crow_app/real_time/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, TextAreaField, IntegerField, SelectField, FileField
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms import ValidationError
from Crow_app.models import User


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')




class RegistrationForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired()])
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired(), EqualTo('password_confirmation', message='Passwords must match')])
    password_confirmation = PasswordField('Password Confirmation', validators=[DataRequired()])
    submit = SubmitField('Register')

    def validate_email(self, email):
        if User.query.filter_by(email=self.email.data).first():
            raise ValidationError('Email has been registered')
    def validate_username(self, username):
        if User.query.filter_by(username=self.username.data).first():
            raise ValidationError('Username has been registered')



class ResetPassword(FlaskForm):
    new_password = PasswordField('Password', validators=[DataRequired(), EqualTo('password_confirmation', message='Passwords must match')])
    password_confirmation = PasswordField('Password Confirmation', validators=[DataRequired()])
    submit = SubmitField('Reset password')

Crow_app/tasks/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, TextAreaField, IntegerField, SelectField, FileField
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms import ValidationError
from Crow_app.models import User


class NewTask(FlaskForm):
    task = TextAreaField("New Task", validators=[DataRequired()])
    user_id = IntegerField(validators=[DataRequired()])
    submit = SubmitField('Add')

Crow_app/products/views.py
from Crow_app import db
from flask import render_template, redirect, request, url_for, Blueprint
from flask_login import login_user, login_required, logout_user, current_user
from Crow_app.models import Product
from Crow_app.products.forms import NewProduct
import os

def new_gallery(name):
    name = f"\{name}"
    location =os.path.abspath(os.path.dirname(__file__))+r"\static\uploads\products"+name
    os.mkdir(location)
    return location

productsr = Blueprint('products', __name__)



################# ROUTES ##################
@productsr.route("/products")
def products():
    products = Product.query.filter_by(status="public")
    return render_template("products.html", products = products)

@productsr.route("/remove-product/<id>")
def remove_product(id):
    product = Product.query.filter_by(id=id).first()
    print(product.name)
    
    db.session.delete(product)
    db.session.commit()

    return redirect(url_for('products.products'))

@productsr.route("/edit-product/<id>",methods=['POST','GET'])
def edit_product(id):
    form = NewProduct()
    product = Product.query.filter_by(id=id).first()

    if form.is_submitted():
        product.name = form.name.data
        if product.name != form.name.data:
            product.gallery = new_gallery(form.name.data)
        product.description = form.description.data
        product.part_id =form.part_id.data
        product.status = form.status.data
       
        
        if request.files['file'].filename !="":
            image = request.files['file']
            path = str(product.gallery + "/pic.png")
            product.main_photo = f"/static/uploads/products/{form.name.data}/pic.png"
            image.save(path)

        db.session.commit()
        return redirect(url_for('products.product', id=product.id, name= product.name ))

    return render_template("edit_product.html", form = form, product =product)



@productsr.route("/product/<name>/<id>")
def product(name, id):
    product = Product.query.get(id)
    return render_template("product.html", product=product)


@productsr.route("/new-products",methods=['POST','GET'])
def new_product():
    form = NewProduct()
    
    if form.is_submitted():
        
        
        product = Product(
            user_id=form.user_id.data,
            owner=form.owner.data,
            name=form.name.data,
            description=form.description.data,
            part_id=form.part_id.data,
            
            main_photo="",
            status=form.status.data)

        image = request.files['file']
        path = str(product.gallery + "/pic.png")
        product.main_photo = f"/static/uploads/products/{form.name.data}/pic.png"
        image.save(path)

        db.session.add(product)
        db.session.commit()
        
        return render_template("product.html", product = product)


    return render_template("new_product.html", form = form)

Crow_app/real_time/views.py
from Crow_app import db
from flask import render_template, redirect, request, url_for, Blueprint
from flask_login import login_user, login_required, logout_user, current_user
from Crow_app.models import User, Task, Product
from Crow_app.users.forms import LoginForm, RegistrationForm

from werkzeug.security import generate_password_hash,check_password_hash
import os
from bme280pi import Sensor
from flask import jsonify
import json
# vluprint setup
real_time = Blueprint('real_time', __name__)


################# ROUTES ##################

@real_time.route('/real_time')
def real_time_page():
    return render_template('real_time.html')

@real_time.route('/real_time/get_status')
def get_status():
    try:
        sensor2 = Sensor(address=0x77)
        data = sensor2.get_data()
    except:
        data = {'temperature': "@@", 'pressure': "@@", 'humidity': "@@"}
    
    return jsonify(data)
   






# @users.route('/user/<username>',methods=['POST','GET'])
# def user(username):
#     form = NewTask()
#     user = current_user
#     products = Product.query.filter_by(user_id=user.id)
#     tasks = Task.query.filter_by(user=user.id)
#     return render_template("user.html", user =user, products= products, tasks = tasks, form= form)

# @users.route('/welcome')
# @login_required
# def welcome_user():
#     return render_template('welcome_user.html')


# @users.route('/reset-password/<username>', methods=['GET','POST'])
# def reset_password(username):
#     form = RegistrationForm()
#     user = User.query.filter_by(username=username).first()

#     if form.is_submitted():
#         user.password_hash = User.reset_password(form.password.data)
#         db.session.commit()
#         msg= "Password reset secssefully!"
#         return render_template("reset_password.html", form=form, msg =msg)

#     return render_template("reset_password.html", form=form, msg ="")

# @users.route('/logout')
# @login_required
# def logout():
#     logout_user()
    
#     return redirect(url_for('users.home'))


# @users.route('/login', methods=['GET','POST'])
# def login():
#     form = LoginForm()
#     msg = "none"
#     if form.is_submitted():
#         user = User.query.filter_by(username=form.username.data.lower()).first()
       
#         if user == None:
#             msg = "Uncorrect email, please try again."
#             return render_template('login.html', form = form, msg = msg)
        

#         if user != None:
#             if user.check_password(form.password.data) == True:
#                 login_user(user)
#                 next = request.args.get('next')
#                 if next == None or not next[0] =='/':
#                     next = url_for('users.home')
#                 return redirect(next)
#             if user.check_password(form.password.data) == False:
#                 msg = "Uncorrect password, please try again."
#                 return render_template('login.html', form = form, msg = msg)
        
#     return render_template('login.html', form = form, msg=msg)



# @users.route('/register', methods=['POST', 'GET'])
# def register():
#     form = RegistrationForm()
#     check_email = User.query.filter_by(email=form.email.data).first()
#     check_username = User.query.filter_by(username=form.username.data).first()
#     msg = "none"
#     if form.is_submitted():

                
#         if check_email != None:
#             msg = "Email is already in use, try to login or register with another Email."
#             print(1)
#             return render_template('register.html', form= form, msg = msg)
        
#         if check_username != None:
#             msg = "Username is already in use, try to login or register with another username."
#             print(2)
#             return render_template('register.html', form= form ,msg = msg)

#         if form.password.data != form.password_confirmation.data:
#             msg = "Password and confirmation password are not the same, try again."
#             return render_template('register.html', form= form ,msg = msg)


#         if check_username == None:
#             if check_email == None:
#                 user = User(
#                     email=form.email.data.lower(),
#                     password=form.password.data,
#                     username=form.username.data.lower()
#                 )

#                 db.session.add(user)
#                 db.session.commit()
                
#                 print(3)
#                 return redirect(url_for('users.login'))

#     return render_template('register.html', form= form, msg=msg)

Crow_app/tasks/views.py
from Crow_app import db
from flask import render_template, redirect, request, url_for, Blueprint
from flask_login import login_user, login_required, logout_user, current_user
from Crow_app.models import Task
from Crow_app.tasks.forms import NewTask
from werkzeug.security import generate_password_hash,check_password_hash
import os


tasksr = Blueprint('tasks', __name__)


@tasksr.route('/delete/<id>', methods=['POST','GET'])
@login_required
def delete_task(id):
        print("sdfsdfs")
        print(id)
        task = Task.query.filter_by(id=id).first()
        db.session.delete(task)
        db.session.commit()
        return redirect(url_for('tasks.tasks'))



@tasksr.route('/task-done/<id>', methods=['POST','GET'])
@login_required
def task_done(id):
        print("sdfsdfs")
        print(id)
        task = Task.query.filter_by(id=id).first()
        task.status = "Done"
        
        db.session.commit()
        return redirect(url_for('tasks.tasks'))


@tasksr.route('/task-waiting/<id>', methods=['POST','GET'])
@login_required
def task_waiting(id):
        print("666")
        print(id)
        task = Task.query.filter_by(id=id).first()
        task.status = "Waiting"
        
        db.session.commit()
        return redirect(url_for('tasks.tasks'))





@tasksr.route("/my-tasks",methods=['GET','POST'])
@login_required
def tasks():
    form = NewTask()
    u = current_user
    user_tasks = Task.query.filter_by(user=u.id)
    
    if form.is_submitted():
        new_task = Task(user_id=form.user_id.data,task=form.task.data,status="Waiting")
        db.session.add(new_task)
        db.session.commit()
        return render_template("tasks.html", form=form,user_tasks=user_tasks )
    return render_template("tasks.html", form=form, user_tasks=user_tasks)

Crow_app/users/views.py
from Crow_app import db
from flask import render_template, redirect, request, url_for, Blueprint
from flask_login import login_user, login_required, logout_user, current_user
from Crow_app.models import User, Task, Product
from Crow_app.users.forms import LoginForm, RegistrationForm
from Crow_app.tasks.forms import NewTask
from werkzeug.security import generate_password_hash,check_password_hash
import os


# vluprint setup
users = Blueprint('users', __name__)


################# ROUTES ##################

@users.route('/')
def home():
    return render_template('home.html')


@users.route('/user/<username>',methods=['POST','GET'])
def user(username):
    form = NewTask()
    user = current_user
    products = Product.query.filter_by(user_id=user.id)
    tasks = Task.query.filter_by(user=user.id)
    return render_template("user.html", user =user, products= products, tasks = tasks, form= form)

@users.route('/welcome')
@login_required
def welcome_user():
    return render_template('welcome_user.html')


@users.route('/reset-password/<username>', methods=['GET','POST'])
def reset_password(username):
    form = RegistrationForm()
    user = User.query.filter_by(username=username).first()

    if form.is_submitted():
        user.password_hash = User.reset_password(form.password.data)
        db.session.commit()
        msg= "Password reset secssefully!"
        return render_template("reset_password.html", form=form, msg =msg)

    return render_template("reset_password.html", form=form, msg ="")

@users.route('/logout')
@login_required
def logout():
    logout_user()
    
    return redirect(url_for('users.home'))


@users.route('/login', methods=['GET','POST'])
def login():
    form = LoginForm()
    msg = "none"
    if form.is_submitted():
        user = User.query.filter_by(username=form.username.data.lower()).first()
       
        if user == None:
            msg = "Uncorrect email, please try again."
            return render_template('login.html', form = form, msg = msg)
        

        if user != None:
            if user.check_password(form.password.data) == True:
                login_user(user)
                next = request.args.get('next')
                if next == None or not next[0] =='/':
                    next = url_for('users.home')
                return redirect(next)
            if user.check_password(form.password.data) == False:
                msg = "Uncorrect password, please try again."
                return render_template('login.html', form = form, msg = msg)
        
    return render_template('login.html', form = form, msg=msg)



@users.route('/register', methods=['POST', 'GET'])
def register():
    form = RegistrationForm()
    check_email = User.query.filter_by(email=form.email.data).first()
    check_username = User.query.filter_by(username=form.username.data).first()
    msg = "none"
    if form.is_submitted():

                
        if check_email != None:
            msg = "Email is already in use, try to login or register with another Email."
            print(1)
            return render_template('register.html', form= form, msg = msg)
        
        if check_username != None:
            msg = "Username is already in use, try to login or register with another username."
            print(2)
            return render_template('register.html', form= form ,msg = msg)

        if form.password.data != form.password_confirmation.data:
            msg = "Password and confirmation password are not the same, try again."
            return render_template('register.html', form= form ,msg = msg)


        if check_username == None:
            if check_email == None:
                user = User(
                    email=form.email.data.lower(),
                    password=form.password.data,
                    username=form.username.data.lower()
                )

                db.session.add(user)
                db.session.commit()
                
                print(3)
                return redirect(url_for('users.login'))

    return render_template('register.html', form= form, msg=msg)

Crow_app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="{{ url_for('static', filename='js/clock.js') }}"></script>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"
    integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+"
    crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">
  <title>Document</title>

</head>

<body>


  <nav class=" navbar-dark bg-dark" style="margin-bottom:2em ; justify-content:normal;  padding-top:5px;
  padding-bottom:5px;">
    <div class="container" style="justify-content:normal;">
      <div class="row">
        <div class="col" style="display:inline-flex; ">
          <button style="border-style:none;" class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <a class="navbar-brand" style="padding-left:15px;
            display:flex;
          justify-content:normal;
          align-items:center;
          font-weight:700;
          font-size:22px;" href="#">Greenhouse</a>
        </div>

        <div class="col" style="  display:flex; justify-content:flex-end; align-items:center;">
          <div id="clock">--:--:--</div>
        </div>
      </div>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{url_for('users.home')}}">Home</a>
          </li>

          {% if current_user.is_authenticated %}

          <!-- <li class="nav-item"></li>
          <a class="nav-link active" aria-current="page"
            href="{{url_for('users.user', username=current_user.username)}}">Profile</a>
          </li> -->


          <li class="nav-item"></li>
          <a class="nav-link active" aria-current="page" href="{{url_for('real_time.real_time_page')}}">Real Time</a>
          </li>
          <!-- <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for('products.products')}}">Products</a>
              </li> -->

          <!-- <li class="nav-item">
                 <a class="nav-link active" aria-current="page" href="{{url_for('tasks.tasks')}}">My tasks</a> 
              </li> -->

          <li class="nav-item dropdown ">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              {{current_user.username}}
            </a>
            <ul class="dropdown-menu">
              <!-- <li><a class="dropdown-item" href="{{url_for('users.reset_password', username=current_user.username)}}">Reset password</a></li> -->
              <li><a class="dropdown-item" href="{{url_for('users.logout')}}">Logout</a></li>

              {% else %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for('users.login')}}">Login</a>
              </li>

              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for('users.register')}}">Register</a>
              </li>
              {% endif %}

            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>




  {% block content %}


  {% endblock %}


</body>

</html>

Crow_app/templates/edit_product.html
{% extends "base.html" %}
{% block content %}

<div class="container" >
    <h1>Edit product - {{product.name}} <img src="{{product.main_photo}}" width="50px" alt=""></h1>

    <form method="post" enctype="multipart/form-data">
        {{form.hidden_tag()}} 
        {{form.user_id(type ="hidden", value = current_user.id)}}
        {{form.owner(type ="hidden", value = current_user.username)}}
        {{form.name.label}}<br>{{form.name(class="form-control",value=product.name)}}<br>
        {{form.description.label}}<br>{{form.description(class="form-control", value=product.description)}}<br>
        {{form.part_id.label}}<br>{{form.part_id(class="form-control", value= product.part_id)}}<br>
        <label for="">New image</label><br><input type = "file" name = "file" class="form-control")/><br>
        {{form.status.label}}<br>{{form.status(class="form-control", value=product.status)}}<br>
        <br>{{form.submit(class="btn btn-primary", value="Update")}}
        
    </form>


</div>


{% endblock%}

Crow_app/templates/home.html
{% extends "base.html" %}
{% block content %}

    <div align ="center" class="jumbotron">
        {% if current_user.is_authenticated %}
            <h1>Hi {{current_user.username}}!</h1>
            <p>Good to see you again.</p>
        {% else %}

            <h1>Welcome!</h1>
            <p>Plaese login or register.</p>
            <a class="btn btn-primary" href="{{url_for('users.login')}}">Login</a>
            <a class="btn btn-primary" href="{{url_for('users.register')}}">Register</a>
        {% endif %}
        
    </div>

{% endblock%}

Crow_app/templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="container" align="center">
    <h1>Login</h1>
    <br>
    <form method="post">
        {{form.hidden_tag()}}
        {{form.username.label}}<br>{{form.username}}<br>
        {{form.password.label}}<br>{{form.password}}<br>
        <br>{{form.submit(class="btn btn-primary")}}
    </form>
    <br>
    {% if msg != "none" %}
    <div class="alert alert-danger" role="alert">
        {{msg}}
    </div>
    {% endif %}
</div>



{% endblock %}

Crow_app/templates/product.html
{% extends "base.html" %}
{% block content %}

<div align="center" class="container" >


    <div class="card" style="width: 18rem;">
        <img src="{{product.main_photo}}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{product.name}}</h5>
          <p class="card-text">{{product.description}}.</p>
        </div>
        <ul align="left"class="list-group list-group-flush">
          <li class="list-group-item"><strong>Part ID:</strong> {{product.part_id}}</li>
          <li class="list-group-item"><strong>Owner:</strong> {{product.owner}}</li>
          <li class="list-group-item"><strong>Status:</strong> {{product.status}}</li>
        </ul>
        <div class="card-body">
            {% if current_user.id == product.user_id %}
            <a href="{{url_for('products.edit_product', id=product.id)}}" class="btn btn-outline-dark">Edit</a>
            <a href="{{url_for('products.remove_product', id=product.id)}}" class="btn btn-outline-danger">Remove</a>
            {% endif %}
            

        </div>
      </div>





</div>

{% endblock%}

Crow_app/templates/products.html
{% extends "base.html" %}
{% block content %}

<div class="container" >
    
    <h1>All Products</h1>
   
    <a href="{{url_for('products.new_product')}}" type="button" class="btn btn-outline-success btn-sm" >Create new product</a>
    <a href="{{url_for('users.user', username=current_user.username)}}" type="button" class="btn btn-outline-success btn-sm" >My products</a>
    


    <div>
        <br>
    </div>
   
    {% for product in products %}
    

        {% if product.status == "public" %}
                
        
        

          <div class="card">
            
            <h5 class="card-header"><a href="{{url_for('products.product', name=product.name, id=product.id)}}">{{product.name}}</a></h5>
            <div class="card-body">
                <img style="border-radius: 10px;" src={{product.main_photo}} alt="" width="100px">
              <h5 class="card-title"> </h5>
              <p class="card-text"><strong>Part ID:</strong> {{product.part_id}}</p>
              <p class="card-text"><strong>Description:</strong> {{product.description}}</p>
              <p class="card-text"><strong>Owner:</strong> {{product.owner}}</p>
              <a href="{{url_for('products.product', name = product.name, id = product.id)}}" class="btn btn-outline-dark">View more</a>
              {% if current_user.id == product.user_id %}
              <a href="{{url_for('products.edit_product', id=product.id)}}" class="btn btn-outline-dark">Edit</a>
              <a href="{{url_for('products.remove_product', id=product.id)}}" class="btn btn-outline-danger">Remove</a>
              {% endif %}
              

            </div>
          </div>
          <br>
        {% endif %}
          {% endfor %}
          
   










</div>


{% endblock%}

Crow_app/templates/tasks.html
{% extends "base.html" %}
{% block content %}

<div class="container" >
    <h1>My tasks</h1>

    <form method="post">
        {{form.hidden_tag()}}
        {{form.user_id(type ="hidden", value = current_user.id)}}
        <br>{{form.task(class="form-control", placeholder="Create new task")}}
        <br>
        {{form.submit(class="btn btn-primary")}}
    </form>
    <br>



    {% for task in user_tasks %}

    {% if task.status == "Done" %}
    <div class="card" style="margin-bottom: 1em;">
        <div class="card-header">
          
        </div>
        <div class="card-body" style="background-color: #ecfdec;">
          <blockquote class="blockquote mb-0">
            <p>{{task.task}}</p>
            <footer class="blockquote-footer"> {{task.status}}
                <div style="display:inline; margin-left:1em">
                <a href="{{url_for('tasks.delete_task', id=task.id)}}" type="button" class="btn btn-outline-danger btn-sm" >Delete</a>
                <a href="{{url_for('tasks.task_waiting', id=task.id)}}" type="button" class="btn btn-outline-dark btn-sm" >Mark as waiting</a>
            </div>
            </footer>

          </blockquote>
        </div>
      </div>
      {% else %}
    
    
    <div class="card" style="margin-bottom: 1em;">
        <div class="card-header">
          
        </div>
        <div class="card-body">
          <blockquote class="blockquote mb-0">
            <p>{{task.task}}</p>
            <footer class="blockquote-footer"> {{task.status}}
                <div style="display:inline; margin-left:1em">
                <a href="{{url_for('tasks.delete_task', id=task.id)}}" type="button" class="btn btn-outline-danger btn-sm" >Delete</a>
                <a href="{{url_for('tasks.task_done', id=task.id)}}" type="button" class="btn btn-outline-success btn-sm" >Mark as done</a>     
            </div>
                         
            </footer>
          </blockquote>
        </div>
      </div>
      {% endif %}
      {% endfor %}


</div>


{% endblock%}

Crow_app/templates/user.html
{% extends "base.html" %}
{% block content %}

<div class="container" >
    <h1>My tasks</h1>
    <a href="{{url_for('tasks.tasks')}}" type="button" class="btn btn-outline-success btn-sm" >Create new task</a>
    <br>

    <br>



    {% for task in tasks %}

    {% if task.status == "Done" %}
    <div class="card" style="margin-bottom: 1em;">
        <div class="card-header">
          
        </div>
        <div class="card-body" style="background-color: #ecfdec;">
          <blockquote class="blockquote mb-0">
            <p>{{task.task}}</p>
            <footer class="blockquote-footer"> {{task.status}}
                <div style="display:inline; margin-left:1em">
                <a href="{{url_for('tasks.delete_task', id=task.id)}}" type="button" class="btn btn-outline-danger btn-sm" >Delete</a>
                <a href="{{url_for('tasks.task_waiting', id=task.id)}}" type="button" class="btn btn-outline-dark btn-sm" >Mark as waiting</a>
            </div>
            </footer>

          </blockquote>
        </div>
      </div>
      {% else %}
    
    
    <div class="card" style="margin-bottom: 1em;">
        <div class="card-header">
          
        </div>
        <div class="card-body">
          <blockquote class="blockquote mb-0">
            <p>{{task.task}}</p>
            <footer class="blockquote-footer"> {{task.status}}
                <div style="display:inline; margin-left:1em">
                <a href="{{url_for('tasks.delete_task', id=task.id)}}" type="button" class="btn btn-outline-danger btn-sm" >Delete</a>
                <a href="{{url_for('tasks.task_done', id=task.id)}}" type="button" class="btn btn-outline-success btn-sm" >Mark as done</a>
            
            </div>
                
                
            </footer>
          </blockquote>
        </div>
      </div>
      {% endif %}
      {% endfor %}
      <br>
      <hr>
      <br>
      <h1>My Products</h1>

      <a href="{{url_for('products.new_product')}}" type="button" class="btn btn-outline-success btn-sm" >Create new product</a>
    <a href="{{url_for('products.products')}}" type="button" class="btn btn-outline-success btn-sm" >All products</a><br>
    
      

    
    <div>
        <br>
    </div>
   
    {% for product in products %}
    
    <div class="card">
            
        <h5 class="card-header"><a href="{{url_for('products.product', name=product.name, id=product.id)}}">{{product.name}}</a></h5>
        <div class="card-body">
            <img style="border-radius: 10px;" src={{product.main_photo}} alt="" width="100px">
          <h5 class="card-title"> </h5>
          <p class="card-text"><strong>Part ID:</strong> {{product.part_id}}</p>
          <p class="card-text"><strong>Description:</strong> {{product.description}}</p>
          <p class="card-text"><strong>Owner:</strong> {{product.user_id}}</p>
          <p class="card-text"><strong>Status:</strong> {{product.status}}</p>
          <a href="{{url_for('products.product', name = product.name, id = product.id)}}" class="btn btn-outline-dark">View more</a>
          {% if current_user.id == product.user_id %}
          <a href="{{url_for('products.edit_product', id=product.id)}}" class="btn btn-outline-dark">Edit</a>
          <a href="{{url_for('products.remove_product', id=product.id)}}" class="btn btn-outline-danger">Remove</a>
          {% endif %}
          

        </div>
      </div>
      <br>
          {% endfor %}
          
 







</div>

{% endblock%}